### ISSUE TITLE
[🚀] [Tracking] Add enhanced command API 

### ISSUE THREAD

**Issue by MarkTwoFive** [jeakfrw/jeak-framework#103]
This is a tracking issue for the new command API implementation.  
  
## Desired features
- [x] Declarative API to build commands and describe their arguments, aliases and sub commands
- [x] Refined parser (based on ANTLR) for commands
- [x] Matcher-like implementation for matching a received command onto the given specs
- [x] Enhanced automated feedback (perm-check, missing or wrong arguments, ...) ( XRef: #13 )
  
## Implementation details
Current development branch: ``t/commands-v2``

**Comment by MarkTwoFive** [comment]
Updated tracking. All features are now available and are undergoing internal tests :slightly_smiling_face: Branch ``bleeding-1.1.X`` has been created for this and will contain all changes for 1.1.0.

**Comment by MarkTwoFive** [comment]
We are currently staging this feature and it looks very good so far :slightly_smiling_face:
